[package]
name = "kumo"
version = "0.1.0"
description = "A Wayland Mobile Browser"
authors = ["Christian Duerr <contact@christianduerr.com>"]
repository = "https://github.com/catacombing/kumo"
rust-version = "1.76.0"
license = "GPL-3.0"
edition = "2021"

[workspace]
members = [
    "funq",
    "funq/funq_derive",
    "libwpe-sys",
    "wpe-backend-fdo-sys",
    "wpe-jsc",
    "wpe-jsc-sys",
    "wpe-webkit",
    "wpe-webkit-sys",
]

[features]
default = []
profiling = ["dep:profiling", "dep:puffin_http"]

[dependencies]
bitflags = "2.5.0"
dashmap = "6.0.1"
dirs = "5.0.1"
funq = { path = "./funq" }
gio = "0.19.2"
glib = "0.19.2"
glutin = { version = "0.32.0", default-features = false, features = ["wayland"] }
indexmap = "2.2.6"
pangocairo = "0.20.0"
pango = { version = "0.20.0", features = ["v1_44"] }
profiling = { version = "1.0.14", optional = true, features = ["profile-with-puffin"] }
puffin_http = { version = "0.16.0", optional = true }
raw-window-handle = "0.6.0"
rusqlite = "0.32.0"
smallvec = "1.13.2"
smithay-client-toolkit = { version = "0.19.1", default-features = false, features = ["xkbcommon"] }
thiserror = "1.0.57"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
wayland-backend = { version = "0.3.3", features = ["client_system"] }
wpe-backend-fdo-sys = { path = "./wpe-backend-fdo-sys" }
wpe-webkit = { path = "./wpe-webkit" }

[build-dependencies]
gl_generator = "0.14.0"

[dev-dependencies]
reqwest = { version = "0.12.2", default-features = false, features = ["default-tls", "blocking"] }
