[package]
name = "kumo"
version = "0.1.0"
description = "A Wayland Mobile Browser"
authors = ["Christian Duerr <contact@christianduerr.com>"]
repository = "https://github.com/catacombing/kumo"
rust-version = "1.76.0"
license = "GPL-3.0"
edition = "2021"

[workspace]
members = [
    "funq",
    "funq/funq_derive",
    "libwpe-sys",
    "wpe-backend-fdo-sys",
    "wpe-jsc",
    "wpe-jsc-sys",
    "wpe-webkit",
    "wpe-webkit-sys",
]

[dependencies]
funq = { path = "./funq" }
glutin = { version = "0.32.0", default-features = false, features = ["wayland"] }
raw-window-handle = "0.6.0"
smithay-client-toolkit = { version = "0.19.1", default-features = false, features = ["xkbcommon"] }
thiserror = "1.0.57"
wayland-backend = { version = "0.3.3", features = ["client_system"] }
wpe-backend-fdo-sys = { path = "./wpe-backend-fdo-sys" }
wpe-webkit = { path = "./wpe-webkit" }
glib = "0.19.2"
gio = "0.19.2"
pangocairo = "0.19.2"
indexmap = "2.2.6"
dirs = "5.0.1"
rusqlite = "0.31.0"

[build-dependencies]
gl_generator = "0.14.0"

[dev-dependencies]
reqwest = { version = "0.12.2", default-features = false, features = ["default-tls", "blocking"] }

[patch.crates-io]
wayland-backend = { git = "https://github.com/chrisduerr/wayland-rs", rev = "46e208db449a91949d5ea5bcadab97df21982343" }
