version: 2.1

defaults: &default-machine
  machine:
    image: ubuntu-2204:current
    resource_class: arm.medium

jobs:
  debian-build:
    <<: *default-machine
    parameters:
      suite:
        type: string
        default: "next"
      architecture:
        type: string
        default: "arm64"
      full_build:
        type: string # yes or no
        default: "yes"
      extra_repos:
        type: string
        default: ""
      host_arch:
        type: string
        default: ""
    steps:
      - run:
          name: << parameters.architecture >> build
          no_output_timeout: 60m
          command: |
            mkdir -p /tmp/buildd-results
            git clone "https://github.com/WHO53/kumo.git" --depth=1 sources
            ls sources
            docker run \
              --rm \
              -e CI \
              -e CIRCLECI \
              -e CIRCLE_BRANCH="${CIRCLE_BRANCH}" \
              -e CIRCLE_SHA1="${CIRCLE_SHA1}" \
              -e CIRCLE_TAG="${CIRCLE_TAG}" \
              -e EXTRA_REPOS="<< parameters.extra_repos >>" \
              -e RELENG_FULL_BUILD="<< parameters.full_build >>" \
              -e RELENG_HOST_ARCH="<< parameters.host_arch >>" \
              -v /tmp/buildd-results:/buildd \
              -v ${PWD}/sources:/buildd/sources \
              --cap-add=SYS_ADMIN \
              --security-opt apparmor:unconfined \
              --security-opt seccomp=unconfined \
              quay.io/droidian/build-essential:<< parameters.suite >>-<< parameters.architecture >> \
              /bin/sh -c "ls ; apt update ; apt install cargo libglib2.0-dev libwpewebkit-2.0-dev libsoup-3.0-dev libwayland-client0 libpango1.0-dev libcairo2-dev libwayland-dev libwpe-1.0-dev libwpebackend-fdo-1.0-dev -y ; cd /buildd/sources ; ls . ; cargo build --release"

            git config --global user.email "notwho53@gmail.com"
            git config --global user.name "WHO53"
            
            git clone https://$PAT@github.com/WHO53/apt.git --depth=1
            cd apt/
            rm -f kumo
            cp ../sources/target/release/kumo .
            git add -A
            git commit -m "Circle CI: ${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1:0:7}"
            git push origin main

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - debian-build:
          context: Orb
